version: '3.8'

services:
  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./src:/usr/src/app/src
      - ./public/upload:/usr/src/app/public/upload
    ports:
      - '3000:3000'
    env_file:
      - ./.env
    depends_on:
      - db
      - db_backup
    networks:
      - backend-network

  db:
    image: mariadb:10.6
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=testuser
      - MYSQL_PASSWORD=password
      - MYSQL_TCP_PORT=3307
      - MYSQL_DATABASE=okoce
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - backend-network

  db_backup:
    image: mariadb:10.6
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=testuser
      - MYSQL_PASSWORD=password
      - MYSQL_TCP_PORT=3308
      - MYSQL_DATABASE=okoce_backup
    volumes:
      - db-backup-data:/var/lib/mysql
    networks:
      - backend-network

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - '8080:80' 
    environment:
      - PMA_ARBITRARY=1 
      - PMA_PORT=3307
      - PMA_HOST=db
      - PMA_PASSWORD=password
      - PMA_USER=testuser
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge

volumes:
  db-data:
  db-backup-data: